server:
  port: 8002

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 60000
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1

spring:
  http:
    encoding:
      charset: utf-8
      enabled: true
      force: true

eureka:
  client:
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: http://${discovery:localhost}:6001/eureka/
  instance:
    # k8s 中的service name 与 spring.application.name 一致才可正常访问
    # 在本地需配置各spring.application.name的hosts
    hostname: ${spring.application.name}

security:
  basic:
    enabled: false

